preprocessing:
  dataset_path: &dataset data/processed/iris.pkl

training:
  dataset_path: *dataset
  model_path: &model_path models/lr.pkl
  model_kw:
    max_iter: 7

evaluate:
  dataset_path: *dataset
  model_path: *model_path
  metrics_path: reports/metrics.json